### PR TITLE
fix usage in precompiled modules: eliminate sourcebuffers

### LINKED ISSUE #449: BoundsError using icxx with string interpolation
I'm using Cxx to call a C++ library (qpOASES, as it happens). This code has worked for a couple of years but recently broke.

I have the following code:

    solver = @cxxnew SQProblem(7, 1)
    myOptions = @cxxnew Options()
    icxx"$myOptions->printLevel = PL_NONE;"
    icxx"$solver->setOptions(*$myOptions);"

What this is supposed to do is create an SQProblem object, create an Options object, set some public member variables in Options, and then set a pointer inside SQProblem to the Options instance. However, as of right now, it gives me the following error instead:

```ERROR: BoundsError: attempt to access 36-element Array{Tuple{AbstractString,Symbol,Int64,Int64,Bool},1} at index [37]
Stacktrace:
 [1] getindex(::Array{Tuple{AbstractString,Symbol,Int64,Int64,Bool},1}, ::Int64) at ./array.jl:728
 [2] #s37#70 at /Users/glenhenshaw/.julia/packages/Cxx/UZsgx/src/cxxstr.jl:705 [inlined]
 [3] #s37#70(::Any, ::Any, ::Any, ::Any) at ./none:0
 [4] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:524
 [5] RMRCsetup(::Manipulator, ::Function, ::Array{Float64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Constraint,1}, ::Float64, ::Float64) at /Users/glenhenshaw/Code/RSGS/PositionControl/RMRC.jl:79
 [6] RMRCsetup at /Users/glenhenshaw/Code/RSGS/PositionControl/RMRC.jl:56 [inlined]
 [7] sam_trajectory() at /Users/glenhenshaw/Code/RSGS/PositionControl/SamTrajectory.jl:117
 [8] top-level scope at REPL[4]:1
```

which corresponds to execution of line 3 in the provided code snippet. This looks to me like is might be a Cxx bug (see level 2 of the stack trace).

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #449.

The `cxx"..."` string macros were caching their code in a global `sourcebuffers` array, and then passing an index into this array with `SourceBuf{id}` to a `@generated` function so that `id` is visible at compile-time (being encoded a type).  However, because this `sourcebuffers` array is generated when Cxx is precompiled, it is incompatible with using Cxx in *other* precompiled modules (which cannot modify `sourcebuffers` in a way that persists beyond precompilation).

Instead, this PR eliminates the `sourcebuffers` array and simply passes *all* of the source data as parameters in a `SourceBuf` type, translating the code to a `Symbol`.  This serves the same purpose of storing the data in a fashion that is persistent and visible in the type-domain, but without causing problems for precompiled modules.

### CODE REVIEW

**Comment by Keno** [comment]
This seems fine to be (Cxx predates precompilation, so it didn't use to be an issue). That said, I don't think it solves the problem entirely. Cxx has a lot of state that does not get serialized (which headers were included, global C++ state, LLVM state). I had at one point hoped to get around to fixing that, but it's a decent size project and was never quite a priority.

**Comment by stevengj** [comment]
@Keno,  I agree that there are a number of other improvements that are possible along these lines.  However, so far I've been able to use Cxx reasonably well in a precompiled module as long as I put some things into `__init__` as needed.

(When using Cxx in a module, I'm also worried about composability with other modules using Cxx, e.g. not using a global compiler instance.)

**Comment by stevengj** [comment]
Okay to merge?

**Comment by Keno** [comment]
Totally fine with me, but @Gnimuc is the current maintainer, so I'd be more comfortable if he hit the button.

**Comment by Gnimuc** [comment]
Merged. All CIs are green.

BTW, @Keno do you have time to take a look at #465. I'm currently stuck in the following error:
```
/Cxx.cpp:1:1: error: 'data' following the 'template' keyword does not refer to a template
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:1242:23: note: declared as a non-template here
    const value_type* data() const _NOEXCEPT  {return _VSTD::__to_raw_pointer(__get_pointer());}
                      ^
/Cxx.cpp:1:1: error: 'size' following the 'template' keyword does not refer to a template
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:946:41: note: declared as a non-template here
    _LIBCPP_INLINE_VISIBILITY size_type size() const _NOEXCEPT
```

**Pull request merged**
