### PR TITLE
Allow and test on Julia v1.2

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by Gnimuc** [comment]
I thought https://github.com/JuliaLang/julia/pull/31272 would be going into v1.2, but it appears it doesn't, at least for now. Anyway, I will rebuild libcxxffi binaries once Julia v1.2 is released.

**Comment by oschulz** [comment]
Thanks for the quick merge, @Gnimuc . Should we register a new version v0.3.1  of Cxx (so that users don't get the Julia version error)?

**Comment by oschulz** [comment]
Ah, v0.3.2, of course

**Comment by Gnimuc** [comment]
Sure, just triggered JuliaRegistrator: https://github.com/JuliaRegistries/General/pull/1127

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
