### PR TITLE
WIP: Fix source build for Julia 1.5

### PR DESCRIPTION
**Pull request by Gnimuc**
- [x] misc. updates for LLVM9
- [ ] fix segfaults

### CODE REVIEW

**Comment by pabloferz** [comment]
Can this be made to depend on `Libffi_jll` and `LLVM_jll`? Or are  there custom patches that need to be applied?

**Comment by Gnimuc** [comment]
Please refer to https://github.com/JuliaInterop/Cxx.jl/pull/466/files#diff-c002a594a18961699f1519658022b71e. Currently, it depends on `LLVM_full_jll@9`.

**Comment by pabloferz** [comment]
Completely missed that. It will rely on Julia's LLVM since julia itself is now using that, right?

**Comment by Gnimuc** [comment]
Yes. Both Cxx.jl and Julia rely on LLVM, but Cxx.jl needs Clang as well.

**Comment by Gnimuc** [comment]
This PR may only fix the C++ side of the package for now. As of the Julia side, it requires more knowledge about the Julia and Clang internals, I'm still learning the details and making nearly no progress.

**Pull request closed without merging**
